# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2025-03-26T18:10:29+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Fruit(Enum):
    APPLE = 'apple'
    BANANA = 'banana'


class Test(BaseModel):
    Fruit_1: Optional[Fruit] = Field(None, alias='Fruit')
