name: Test and Lint

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
            manifest-path: pyproject.toml
            pixi-version: v0.30.0
            cache: false
      - run: pixi run test
