name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cache: [true, false]
    runs-on: ${{ matrix.os }}
    name: default ${{ matrix.cache == true && 'with' || 'without' }} cache (${{ matrix.os }})
    steps:
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          manifest-path: pyproject.toml
          cache: ${{ matrix.cache }}
      - run: |
          pixi run test