name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  build:
  - uses: prefix-dev/setup-pixi@v0.8.0
  with:
    cache: true
    cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    pixi-version: v0.30.0
    cache: true
  - run: pixi run test

